services:

  db:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../env_example.env

  web:
    build: ../
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
    env_file:
      - ../env_example.env
    command: sh -c "gunicorn --bind 0.0.0.0:8000 tree_menu.wsgi"

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web
      - db
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/  

volumes:
  postgres_data: 
  static_value:  
